FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY dist ./dist
COPY src/services/job_service ./src/services/job_service
COPY src/shared ./src/shared
ENV NODE_ENV=production
CMD ["node", "dist/services/job_service/main.js"]
