FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build
COPY src/services/job_service/start.js ./dist/services/job_service/start.js
ENV NODE_ENV=production
ENV PORT=8080
CMD ["node", "dist/services/job_service/start.js"]
