FROM node:20-alpine
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile
COPY tsconfig.json ./
COPY src ./src
RUN pnpm run build
COPY src/services/job-service/start.js ./dist/services/job-service/start.js
ENV NODE_ENV=production
ENV PORT=8080
COPY configs/ ./configs/
CMD ["node", "dist/services/job-service/start.js"]
